package com.iprism.medrayder.utils

object Constants {

    // production

    const val BASE_URL = "https://medrayder.in/bharosa/app/ws/"
    const val IMAGES_BASE_URL = "https://medrayder.in/bharosa/"

    // Testing

    /*const val BASE_URL = "https://medconnect.org.in/bharosa/app/ws/"
    const val IMAGES_BASE_URL = "https://medconnect.org.in/bharosa/"*/


    const val LOGIN_ENDPOINT = "login"
    const val RESEND_OTP_ENDPOINT = "resend_otp"
    const val HOME_PAGE_ENDPOINT = "home_page"
    const val FAMILY_MEMBERS_ENDPOINT = "family_members"
    const val USER_DROPDOWN_ENDPOINT = "user_dropdowns"
    const val REGISTER_ENDPOINT = "registration"
    const val ADD_FAMILY_MEMBER_ENDPOINT = "add_family_members"
    const val WALLET_ENDPOINT = "wallet"
    const val WALLET_HISTORY_ENDPOINT = "wallet_history"
    const val ADDRESS_ENDPOINT = "user_address"
    const val ADDRESS_LIST_ENDPOINT = "get_user_address"
    const val SUBSCRIPTION_ENDPOINT = "get_health_cards"
    const val GET_SINGLE_SUBSCRIPTION_ENDPOINT = "get_single_health_card"
    const val SUBSCRIPTION_DETAILS_ENDPOINT = "user_subscription"
    const val PROFILE_ENDPOINT = "profile"
    const val PROFILE_EDIT_ENDPOINT = "edit_profile"
    const val MED_LOCKER_ENDPOINT = "med_locker"
    const val TREATMENT_PLANING_ENDPOINT = "treatment_planning"
    const val CONTACT_US_ENDPOINT = "contact_us"
    const val FILTERS_ENDPOINT = "filters"
    const val NOTIFICATIONS_ENDPOINT = "notifications"
    const val CONTENT_PAGES_ENDPOINT = "content_pages"

    const val ONLINE_DOCTOR_SPECIALITIES_ENDPOINT = "online_doctor_specialities"
    const val ONLINE_DOCTORS_ENDPOINT = "online_doctors"
    const val ONLINE_DOCTORS_BOOKING_DETAILS_ENDPOINT = "online_doctor_booking_details"
    const val ONLINE_DOCTORS_COUPONS_ENDPOINT = "online_doctor_coupons"
    const val ONLINE_DOCTOR_BOOKING_ENDPOINT = "online_doctor_booking"
    const val ONLINE_DOCTOR_BOOKING_HISTORY_ENDPOINT = "online_doctor_bookings_history_active"
    const val ONLINE_DOCTOR_BOOKING_HISTORY_COMPLETED_ENDPOINT = "online_doctor_bookings_history_completed"
    const val ONLINE_DOCTOR_SINGLE_BOOKING_COMPLETED_ENDPOINT = "online_doctor_single_booking_details"
    const val ONLINE_DOCTOR_RATING_ENDPOINT = "online_doctor_rating"

    const val HOSPITALS_ENDPOINT = "all_hospitals"
    const val MAIN_DATA_ENDPOINT = "main_data"
    const val HOSPITAL_DETAILS_ENDPOINT = "total_main_data"
    const val HOSPITAL_DOCTORS_ENDPOINT = "doctors"
    const val HOSPITAL_DOCTOR_TIME_SLOTS_ENDPOINT = "doctor_booking_details"
    const val HOSPITAL_DOCTOR_BOOKING_ENDPOINT = "doctor_booking"
    const val HOSPITAL_DOCTOR_COUPONS_ENDPOINT = "doctor_coupons"
    const val HOSPITAL_DOCTOR_BOOKING_HISTORY_ENDPOINT = "doctor_bookings_history_active"
    const val HOSPITAL_DOCTOR_BOOKING_HISTORY_COMPLETED_ENDPOINT = "doctor_bookings_history_completed"
    const val HOSPITAL_DOCTOR_BOOKING_SINGLE_DETAILS_ENDPOINT = "doctor_single_booking_details"
    const val HOSPITAL_ADMIT_BOOKING_ENDPOINT = "admit_booking"
    const val HOSPITAL_ADMIT_ONGOING_BOOKINGS_ENDPOINT = "admit_bookings_ongoing"
    const val HOSPITAL_ADMIT_COMPLETED_BOOKINGS_ENDPOINT = "admit_bookings_completed"
    const val HOSPITAL_ADMIT_BOOKING_DETAILS_ENDPOINT = "single_admit_booking_details"
    const val HOSPITAL_AMBULANCE_BOOKING_ENDPOINT = "ambulance_booking"
    const val HOSPITAL_AMBULANCE_ONGOING_BOOKINGS_ENDPOINT = "ambulance_bookings_ongoing"
    const val HOSPITAL_AMBULANCE_COMPLETED_BOOKINGS_ENDPOINT = "ambulance_bookings_completed"
    const val HOSPITAL_AMBULANCE_TRACKING_ENDPOINT = "ambulance_tracking"
    const val HOSPITAL_DOCTOR_RATING_ENDPOINT = "hospital_doctor_rating"

    const val HOSPITAL_MED_CATEGORIES_ENDPOINT = "pharmacy_categories"
    const val HOSPITAL_MED_PRODUCTS_ENDPOINT = "hospital_pharmacy_products"
    const val HOSPITAL_MED_PRODUCT_ADD_TO_CART_ENDPOINT = "hospital_pharmacy_product_add_to_cart"
    const val HOSPITAL_MED_PRODUCT_CART_ENDPOINT = "hospital_pharmacy_product_cart"
    const val HOSPITAL_MED_PRODUCT_BOOKING_ENDPOINT = "hospital_pharmacy_product_booking"
    const val HOSPITAL_MED_COUPONS_ENDPOINT = "hospital_pharmacy_product_coupons"
    const val HOSPITAL_MED_ONGOING_BOOKINGS_ENDPOINT = "hospital_pharmacy_ongoing_bookings"
    const val HOSPITAL_MED_COMPLETED_BOOKINGS_ENDPOINT = "hospital_pharmacy_completed_bookings"
    const val HOSPITAL_MED_BOOKINGS_DETAILS_ENDPOINT = "hospital_pharmacy_single_booking_details"
    const val HOSPITAL_MED_PRESCRIPTION_BOOKING_ENDPOINT = "hospital_pharmacy_medicine_booking"

    const val HOSPITAL_DIAGNOSTIC_TESTS_ENDPOINT = "hospital_diagnostic_tests"
    const val HOSPITAL_DIAGNOSTIC_TIME_ENDPOINT = "hospital_diagnostic_test_booking_details"
    const val HOSPITAL_DIAGNOSTIC_BOOKING_ENDPOINT = "hospital_diagnostic_booking"
    const val HOSPITAL_DIAGNOSTIC_COUPONS_ENDPOINT = "hospital_diagnostic_coupons"
    const val HOSPITAL_DIAGNOSTIC_ONGOING_BOOKINGS_ENDPOINT = "hospital_diagnostic_ongoing_bookings"
    const val HOSPITAL_DIAGNOSTIC_COMPLETED_BOOKINGS_ENDPOINT = "hospital_diagnostic_completed_bookings"
    const val HOSPITAL_DIAGNOSTIC_BOOKING_DETAILS_ENDPOINT = "hospital_diagnostic_single_booking_details"
    const val HOSPITAL_DIAGNOSTIC_PRESCRIPTION_BOOKING_ENDPOINT = "hospital_diagnostic_prescription_booking"

    const val DIAGNOSTIC_CENTERS_ENDPOINT = "diagnostics_main_data"
    const val DIAGNOSTIC_TESTS_ENDPOINT = "diagnostic_tests"
    const val DIAGNOSTIC_BOOKING_DETAILS_ENDPOINT = "diagnostic_test_booking_details"
    const val DIAGNOSTIC_COUPONS_ENDPOINT = "diagnostic_coupons"
    const val DIAGNOSTIC_BOOKING_ENDPOINT = "diagnostic_booking"
    const val DIAGNOSTIC_PRESCRIPTION_BOOKING_ENDPOINT = "diagnostic_prescription_booking"
    const val DIAGNOSTIC_TEST_ONGOING_BOOKINGS_ENDPOINT = "diagnostic_ongoing_bookings"
    const val DIAGNOSTIC_TEST_COMPLETED_BOOKINGS_ENDPOINT = "diagnostic_completed_bookings"
    const val DIAGNOSTIC_TEST_BOOKING_DETAILS_ENDPOINT = "diagnostic_single_booking_details"

    const val PHARMACIES_ENDPOINT = "pharmacy_main_data"
    const val PHARMACY_DETAILS_ENDPOINT = "total_pharmacy_main_data"
    const val PHARMACY_PRODUCTS_ENDPOINT = "pharmacy_products"
    const val PHARMACY_PRODUCT_ADD_TO_CART_ENDPOINT = "pharmacy_product_add_to_cart"
    const val PHARMACY_PRODUCT_CART_ENDPOINT = "pharmacy_product_cart"
    const val PHARMACY_COUPONS_ENDPOINT = "pharmacy_product_coupons"
    const val BOOK_PHARMACY_PRODUCT_ENDPOINT = "pharmacy_product_booking"
    const val PHARMACY_ONGOING_BOOKINGS = "pharmacy_ongoing_bookings"
    const val PHARMACY_COMPLETED_BOOKINGS = "pharmacy_completed_bookings"
    const val PHARMACY_BOOKING_DETAILS_ENDPOINT = "pharmacy_single_booking_details"
    const val PHARMACY_PRESCRIPTION_BOOKING_ENDPOINT = "pharmacy_medicine_booking"

    const val LAB_CENTERS_ENDPOINT = "lab_tests_main_data"
    const val LAB_TESTS_ENDPOINT = "lab_tests"
    const val LAB_BOOKING_DETAILS_ENDPOINT = "lab_test_booking_details"
    const val LAB_COUPONS_ENDPOINT = "lab_test_coupons"
    const val LAB_BOOKING_ENDPOINT = "lab_test_booking"
    const val LAB_PRESCRIPTION_BOOKING_ENDPOINT = "lab_test_prescription_booking"
    const val LAB_TEST_ONGOING_BOOKINGS_ENDPOINT = "lab_test_ongoing_bookings"
    const val LAB_TEST_COMPLETED_BOOKINGS_ENDPOINT = "lab_test_completed_bookings"
    const val LAB_TEST_BOOKING_DETAILS_ENDPOINT = "lab_test_single_booking_details"

    const val DISCONNECT_NOTIFICATION_ENDPOINT = "disconnect_notification"
    const val CREATE_CASH_FREE_ENDPOINT = "create_cashfree_order"
    const val CHECK_PAYMENT_ENDPOINT = "check_payment"
    const val E_CARD_ENDPOINT = "ecard"
}
